### ISSUE TITLE
Install/Uninstall of modification has double-slash for additional theme actions

### ISSUE THREAD

**Issue by SugarD-x** [SimpleDesk/SimpleDesk#112]
#### Description
When installing or uninstalling the modification, if additional themes are installed, the option to affect them includes a double-slash in the path.

### Steps to reproduce
1. Install or uninstall the modification with multiple themes installed.
2. The path will contain a double-slash for the section where actions are taken against additional themes.

### Environment (complete as necessary)
- Version/Git revision: Latest repository files.
- Database Type: MySQL
- Database Version: 8.0.12 - MySQL Community Server - GPL

### Additional information/references
For an example:
`./Themes/theme1//images/admin/shd`

**Comment by jdarwood007** [comment]
What are the urls like in your theme settings?  I tested this with another theme and it works fine.
Install is fine and no issues.  Switching to that theme shows no double slashes in the source code.

The themes urls should not end in /

**Comment by SugarD-x** [comment]
Ah, yes. For some reason just a single setting for the theme had a trailing slash for some reason. (I blame the theme maker). I'll close this then. Thanks!
