### ISSUE TITLE
Bug icons

### ISSUE THREAD

**Issue by jdarwood007** [SimpleDesk/SimpleDesk#15]
#### Reference [SimpleDesk Website: Bug icons](https://www.simpledesk.net/community/index.php?topic=1350)
===
__SimpleDesk version:__ SimpleDesk 2.0.1
__SMF version:__  SMF 2.1 Beta 2

Latest revision from the GitHub. Download is of branch smf21 from 08.11.2015.

MySQLi version: 5.6.25
PHP: 5.6.11
SMF 2.1 Beta 2 is from the latest revision from the GitHub 08.11.2015
__Some icons are not displayed:__

<img src="http://scaricare.de/upload/shd/bug_menu_index.png" alt="Image" />

<img src="http://scaricare.de/upload/shd/bug_menu_coresetting.png" alt="Image" />

<span style="font-size:1em">__My suggested solution:__</span>

Creates a new folder &quot;icons&quot; in root/Themes/default/images/simpledesk/. Inserts the icons in this folder &quot;icons&quot; and the &quot;helpdesk_icons.css&quot; in root/Themes/default/css/:

<img src="http://scaricare.de/upload/shd/shd_admin_icons.png" alt="Image" />

<img src="http://scaricare.de/upload/shd/shd_generic_icons.png" alt="Image" />
<a href="http://scaricare.de/upload/shd/new_helpdesk_icons_css.zip" title="Download icons and helpdesk_icons.css">Download icons and helpdesk_icons.css</a>

__Open root/Sources/sd_source/Subs-SimpleDeskAdmin.php__

find
<code>function shd_admin_bootstrap(&amp;{&dollarfix;$}admin_areas)
{
    global {&dollarfix;$}sourcedir, {&dollarfix;$}modSettings, {&dollarfix;$}txt, {&dollarfix;$}context, {&dollarfix;$}scripturl;</code>
replaces with
<code>function shd_admin_bootstrap(&amp;{&dollarfix;$}admin_areas)
{
    global {&dollarfix;$}sourcedir, {&dollarfix;$}modSettings, {&dollarfix;$}txt, {&dollarfix;$}context, {&dollarfix;$}scripturl, {&dollarfix;$}settings;

    // Load some extra CSS
    {&dollarfix;$}context&#91;&#039;html_headers&#039;] .= &#039;
    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;&#039; . {&dollarfix;$}settings&#91;&#039;default_theme_url&#039;] . &#039;/css/helpdesk_icons.css&quot; /&gt;&#039;;</code>
find
<code>                    &#039;icon&#039; =&gt; &#039;shd/simpledesk.png&#039;,</code>
replaces with
<code>                    &#039;icon&#039; =&gt; &#039;shd_simpledesk&#039;,</code>
find
<code>                    &#039;icon&#039; =&gt; &#039;shd/options.png&#039;,</code>
replaces with
<code>                    &#039;icon&#039; =&gt; &#039;shd_options&#039;,</code>
find
<code>                    &#039;icon&#039; =&gt; &#039;shd/cannedreplies.png&#039;,</code>
replaces with
<code>                    &#039;icon&#039; =&gt; &#039;shd_cannedreplies&#039;,</code>
find
<code>                    &#039;icon&#039; =&gt; &#039;shd/custom_fields.png&#039;,</code>
replaces with
<code>                    &#039;icon&#039; =&gt; &#039;shd_custom_fields&#039;,</code>
find
<code>                    &#039;icon&#039; =&gt; &#039;shd/departments.png&#039;,</code>
replaces with
<code>                    &#039;icon&#039; =&gt; &#039;shd_departments&#039;,</code>
find
<code>                    &#039;icon&#039; =&gt; &#039;shd/permissions.png&#039;,</code>
replaces with
<code>                    &#039;icon&#039; =&gt; &#039;shd_permissions&#039;,</code>
find
<code>                    &#039;icon&#039; =&gt; &#039;shd/plugins.png&#039;,</code>
replaces with
<code>                    &#039;icon&#039; =&gt; &#039;shd_plugins&#039;,</code>
find
<code>                    &#039;icon&#039; =&gt; &#039;shd/maintenance.png&#039;,</code>
replaces with
<code>                    &#039;icon&#039; =&gt; &#039;shd_maintenance&#039;,</code>

__Open root/Sources/sd_source/Subs-SimpleDesk.php__

find
<code>function shd_main_menu(&amp;{&dollarfix;$}menu_buttons)
{
    global {&dollarfix;$}context, {&dollarfix;$}txt, {&dollarfix;$}scripturl, {&dollarfix;$}modSettings;</code>
replaces with
<code>function shd_main_menu(&amp;{&dollarfix;$}menu_buttons)
{
    global {&dollarfix;$}context, {&dollarfix;$}txt, {&dollarfix;$}scripturl, {&dollarfix;$}modSettings, {&dollarfix;$}settings;

    // Load some extra CSS
    {&dollarfix;$}context&#91;&#039;html_headers&#039;] .= &#039;
    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;&#039; . {&dollarfix;$}settings&#91;&#039;default_theme_url&#039;] . &#039;/css/helpdesk_icons.css&quot; /&gt;&#039;;</code>

[size=1em]__After solution:__[/size]

<img src="http://scaricare.de/upload/shd/menu_index.png" alt="Image" />

<img src="http://scaricare.de/upload/shd/menu_coresetting.png" alt="Image" />

<img src="http://scaricare.de/upload/shd/menu_helpdesk.png" alt="Image" />

**Comment by wintstar** [comment]
only thing missing is the change in package-info.xml
