### ISSUE TITLE
Bug Profile Ticket Content

### ISSUE THREAD

**Issue by jdarwood007** [SimpleDesk/SimpleDesk#28]
#### Reference [SimpleDesk Website: Bug Profile Ticket Content](https://www.simpledesk.net/community/index.php?topic=2170)
# 

In User Profiles are the ticket Buttons &quot;Post new ticket&quot; and &quot;Vie my ticket&quot; are shifted.

<img src="http://scaricare.de/upload/shd/bug_profile_content.png" alt="Image" />

**Comment by wintstar** [comment]
Fixed https://github.com/wintstar/Testing/commit/5717e10d5a98d6561416d04d081dff35db0a2347

![bug_profile_content-1](https://cloud.githubusercontent.com/assets/2753863/11611047/7491c638-9bb9-11e5-8565-36d0181b42d9.png)

**Comment by Antes** [comment]
Why not just use "button" class, while I was working on SD/2.1 i was moving more towards to core-css classes. I kinda suggest the same if you take-over the adaption job.

https://github.com/margarett/SimpleDesk_SMF2.1/pull/2/files

**Comment by jdarwood007** [comment]
Mostly because we have our own style kinda.

@wintstar, I will incorperate your changes here shortly as well.  The breakage came from me backporting .description css class to fix stuff in the helpdesk admin section.  I've made changes that works around it for now.

**Comment by jdarwood007** [comment]
@wintstar,
Actually, you can issue a PR if you want.  On your testing branch you can issue a PR to the smf21 branch here and reference this issue (#28).  It will link it up and then I just hit approve.  Your changes will get merged in.

I don't do it (but I should), but all changes should come from your own repo and then merged in.

**Comment by wintstar** [comment]
Since I'm not that familiar with github, I have this first created so the "separate branch". I'm working to understand github shell. 
In the template must also still a lot for the mobile design be changed.

**Comment by jdarwood007** [comment]
I use SourceTree.app.  Knowing the cli commands is nice, but when you want it, a GUI interface saves a lot of time.

**Comment by wintstar** [comment]
Yes, I am also testing the SourceTree and Github for windows.

**Comment by Arantor** [comment]
@Antes the reason for not using a button class is that 5 years ago when this was written, we didn't have one and we wanted a semi-distinctive look...

**Comment by Antes** [comment]
I know, I was thinking maybe with adoption to SMF2.1 this will change and more core-css usage etc... :P

**Comment by jdarwood007** [comment]
@Arantor Glad to see you around.

@Antes Are you able to get me a mergeable PR?  I wouldn't mind honestly if it had more compatibility with the new 2.1 default theme and templates.  The one thing about SimpleDesk is it has always looked really nice, so I don't really want to loose that.  I am no designer, i'm a programmer.  So getting the UI aspect down is not my strong suit.

**Comment by PaulLaufer** [comment]
@Arantor Good to see you! When are you going to make it to California? :)

**Comment by jdarwood007** [comment]
This looks resolved
