### ISSUE TITLE
SCEditor

### ISSUE THREAD

**Issue by Labradoodle-360** [SimpleDesk/SimpleDesk#40]
Currently posting a ticket or a response has a fairly broken editor because it doesn't fully use SCEditor from the looks of things.

**Comment by jdarwood007** [comment]
Far as I can tell, things work fine besides a UI issue.  The rich editor is disabled by default on SimpleDesk.

**Comment by jdarwood007** [comment]
#59 Helps resolve that issue.  That took a while to find.

**Comment by jdarwood007** [comment]
Closing this as the SCEditor is now in place properly.
