### ISSUE TITLE
text=auto

### ISSUE THREAD

**Issue by Antes** [SimpleDesk/SimpleDesk#63]
Is there any reason why we are not changing to auto. That fixes my local issue of weird line-endings https://github.com/SimpleDesk/SimpleDesk/blob/smf21/.gitattributes#L2

**Comment by jdarwood007** [comment]
I think it should be
````
* text eol=lf
````

Can you test?

**Comment by jdarwood007** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/.gitattributes

Also why doesn't this affect you on SMF?

I tested forcing eol=lf, it does cause a few files to show up needing fixed.  I can fix that in a PR and that should correct that for the rest of your PRs.

**Comment by Antes** [comment]
* text eol=lf is not working for me but only text=auto.

**Comment by Antes** [comment]
We good in this part.
