### ISSUE TITLE
Re-order custom fields

### ISSUE THREAD

**Issue by jdarwood007** [SimpleDesk/SimpleDesk#84]
#### Reference [SimpleDesk Website: Re-order custom fields](https://www.simpledesk.net/community/index.php?topic=2076)
===
Add ability to reorder custom fields.

1. Add a sort column.
2. Default to current index during upgrade.
3. Add UI aspect to move around in ACP
4. Update front end to use the order.

**Comment by frandominguez03** [comment]
Can be closed?
