### ISSUE TITLE
Undefined index new

### ISSUE THREAD

**Issue by jdarwood007** [SimpleDesk/SimpleDesk#85]
Undefined index: new in C:\wamp64\www\simple\Themes\default\sd_template\SimpleDesk.template.php on line 324

**Comment by SugarD-x** [comment]
When viewing `?action=helpdesk;sa=main` in SMF 2.1 RC1, this is still spamming the error log, although the lines vary around the same area as line 324.

**Comment by jdarwood007** [comment]
Was this a upgrade from 2.0?
I can't reproduce either at this time.

**Comment by SugarD-x** [comment]
It was a fresh install of 2.1 Beta 3 that was later upgraded to the pseudo 2.1 Beta 4, then 2.1 RC1 before installing this mod.

**Comment by SugarD-x** [comment]
I'm still getting this on the current repo files. It is very odd to reproduce, though. I've had to go to the main Helpdesk page, then go to the Admin section of the Helpdesk, then back to the main Helpdesk page to trigger the errors, which don't show up consistently, even when refreshing the page.

**Comment by jdarwood007** [comment]
Do you have reproducible steps on that?

Theme shouldn't mater since it is using the default theme for SD.

**Comment by SugarD-x** [comment]
My first edit to my previous reply is the only way I can reproduce this. It is very inconsistent. It looks like something on page load with the mod installed is triggering the errors. Beyond that I can't narrow it down.
