### ISSUE TITLE
11 errors after installing mod

### ISSUE THREAD

**Issue by frandominguez03** [SimpleDesk/SimpleDesk#93]
Using latest commit of SMF 2.1: https://github.com/SimpleMachines/SMF2.1/commit/95a5a1d4ebaabbce301c1db2f00f3309e7125c8d

Got 11 errors in the log after installing the mod;
![screenshot_1](https://user-images.githubusercontent.com/10365222/44099262-8c7d73ca-9fe2-11e8-8985-db1f04fa70be.png)
![screenshot_2](https://user-images.githubusercontent.com/10365222/44099263-8ca2d4d0-9fe2-11e8-8ae9-b3692ec52d63.png)
![screenshot_3](https://user-images.githubusercontent.com/10365222/44099265-8cdac066-9fe2-11e8-9764-c4d21c8faa1a.png)

Is backtrace needed?

**Comment by jdarwood007** [comment]
This is actually a SMF bug.  https://github.com/SimpleMachines/SMF2.1/issues/4926

Not sure what we can do to work around it yet.

**Comment by SugarD-x** [comment]
This is still present with SMF 2.1 RC1 also.

**Comment by frandominguez03** [comment]
Could you actually install the mod? I remember trying a few days ago and not being able to. I'll try again when I can.

**Comment by SugarD-x** [comment]
I was, however I had to go back to the Package Manager and do it again. If you upload it and try to install it directly, it just shows an install page with blank actions and an install button that does nothing. I'm not sure if this is an emulation bug in SMF 2.1 RC1, or any issue with SimpleDesk.

**Comment by frandominguez03** [comment]
I'm not sure, but that's probably because there are no rules for installing it with SMF 2.1 RC1, as in package-info.xml:

https://github.com/SimpleDesk/SimpleDesk/blob/e94e0cff46611728234da5243f1be639039b8498/package-info.xml#L17

I haven't digged, so I'm probably wrong

**Comment by SugarD-x** [comment]
> I'm not sure, but that's probably because there are no rules for installing it with SMF 2.1 RC1, as in package-info.xml:
> 
> [SimpleDesk/package-info.xml](https://github.com/SimpleDesk/SimpleDesk/blob/e94e0cff46611728234da5243f1be639039b8498/package-info.xml#L17)
> 
> Line 17 in [e94e0cf](/SimpleDesk/SimpleDesk/commit/e94e0cff46611728234da5243f1be639039b8498)
> 
>  <install for="2.1 Beta 3, 2.1 Beta 4"> 
> I haven't digged, so I'm probably wrong
Ah, that could definitely explain it! I opened a bug report for that particular issue, (#99), so hopefully it is something that simple.

**Comment by jdarwood007** [comment]
I've got a fix issued up to SMF repo that should clear this up by doing a silent ignore of hooks during package install/removal.  If it merges, it will be in the next RC.

**Comment by SugarD-x** [comment]
Awesome! It is definitely still present in SMF 2.1 RC1 with the latest SimpleDesk repo, so it'll be nice once they have that fixed. The spam is quite worrisome if you don't know what is going on. xD

**Comment by jdarwood007** [comment]
The SMF repo merged these changes.  I will close this, it will be fixed in the next SMF release.  It can be verified by using the git version of SMF 2.1.
