### ISSUE TITLE
Undefinex index: shd_display_avatar

### ISSUE THREAD

**Issue by frandominguez03** [SimpleDesk/SimpleDesk#94]
Fresh install with latest commit from SMF2.1

Received the following error:
![screenshot_1](https://user-images.githubusercontent.com/10365222/44206663-d6f04800-a15a-11e8-850c-729214f061af.png)

Steps to reproduce:

- Admin > Helpdesk > Options > Display Options > Check "Display avatars in replies to a ticket?".

**Comment by jdarwood007** [comment]
Unable to reproduce at this time.  Reopen if it is still occuring.
